import React, { createContext, useContext, useState } from "react";

const DICT = {
  id: {
    tagline: "Blockchain Traceability",
    login_heading: "Silakan masuk",
    login_sub: "Gunakan akun yang telah diundang admin.",
    email: "Email",
    password: "Kata Sandi",
    sign_in: "Masuk",
    verifying: "Memverifikasi...",
    quick_fill: "Isi Cepat Demo",
    public_verify: "→ Verifikasi Produk (Publik)",
    live_network: "Live Network",
    validators: "3 Validators",
    welcome: "Selamat datang",
    dashboard_title: "Dasbor Operasional",
    dashboard_sub: "Ringkasan real-time rantai pasok tembakau — Petani hingga Konsumen.",
    block_height: "Block Height",
    latency: "Latency",
    validators2: "Validators",
    data_sync: "Data Sync",
    synced: "SYNCED",
    active_harvests: "Batch Panen Aktif",
    collections: "Batch Pengumpulan",
    production_batches: "Batch Produksi",
    shipments: "Pengiriman",
    retail_batches: "Ritel Terdaftar",
    trace_records: "Rekaman Traceability",
    quality_compliance: "Kepatuhan Kualitas",
    open_exceptions: "Anomali Terbuka",
    supply_chain: "Visualisasi Rantai Pasok",
    journey: "Journey Batch Horizontal",
    search_batch: "→ Cari Batch",
    verified: "✓ Terverifikasi",
    exception: "⚠ Anomali",
    pending: "⚡ Pending",
    net_status: "Blockchain Network",
    healthy: "HEALTHY",
    consumer_portal: "Portal Konsumen",
    logout: "Keluar",
    nav_dashboard: "Dasbor",
    nav_harvest: "Registrasi Panen",
    nav_collection: "Pengumpulan",
    nav_production: "Produksi",
    nav_shipment: "Pengiriman",
    nav_sales: "Penjualan Ritel",
    nav_trace: "Traceability",
    nav_explorer: "Blockchain Explorer",
    nav_contracts: "Smart Contracts",
    nav_quality: "IoT & Kualitas",
    nav_exceptions: "Anomali",
    nav_analytics: "Analitik",
    nav_audit: "Audit Log",
    nav_users: "Manajemen User",
    verify_heading: "Portal Verifikasi Konsumen",
    verify_sub: "Scan QR atau masukkan Product ID untuk memeriksa keaslian tembakau Anda.",
    verify_btn: "Verifikasi",
    authentic: "✓ TERVERIFIKASI OTENTIK",
    authentic_sub: "Asli Indonesia · Blockchain Verified",
    not_authentic: "✗ TIDAK TERVERIFIKASI",
    variety: "Varietas",
    cultivation: "Asal Kebun",
    harvest_date: "Tanggal Panen",
    grade: "Grade",
    chain_journey: "Journey Rantai Pasok",
    download_cert: "Unduh Sertifikat Keaslian (PDF)",
    hero_body: "Setiap panen, penimbangan, produksi, pengiriman, dan penjualan dicatat sebagai blok immutable dengan hash SHA-256 di ledger blockchain.",
    map_title: "Peta Perjalanan",
    map_from: "Kebun Asal",
    map_to: "Toko Ritel",
    scanned_count: "Sudah dipindai",
    times: "kali",
    cancel: "Batal",
    product_not_found: "Produk tidak ditemukan",
    camera_unavailable: "Kamera tidak tersedia",

    // Harvest form
    farmer_module: "Modul Petani",
    harvest_reg: "Registrasi Panen Tembakau",
    variety_label: "Varietas Tembakau",
    location_label: "Lokasi Kebun",
    gps_label: "Koordinat GPS",
    weight_kg: "Berat Total (kg)",
    plant_age: "Umur Tanaman (hari)",
    moisture_pct: "Kadar Air (%)",
    initial_grade: "Grade Awal",
    submit_harvest: "Terbitkan Smart Contract Panen (SC-001)",
    signing_block: "Menandatangani blok...",
    last_tx: "Transaksi Terakhir",
    batch_id: "Batch ID",
    block_num: "Block #",
    hash: "Hash",
    no_tx_yet: "Belum ada transaksi. Isi form untuk mencatat panen pertama Anda ke ledger.",
    save_fail: "Gagal simpan",
    saved_to_ledger: "tercatat di ledger",

    // Collection form
    collector_module: "Modul Pengepul",
    collection_rec: "Pencatatan Pengumpulan",
    source_harvest: "Batch Panen Sumber",
    pick_hb: "Pilih HB...",
    weight_received: "Berat Diterima (kg)",
    leaf_grade: "Grade Daun",
    drying_method: "Metode Pengeringan",
    sort_notes: "Catatan Sortir",
    submit_collection: "Tandatangani & Teruskan ke Pabrik (SC-002)",
    available_harvests: "Batch Panen Tersedia",
    no_harvest_available: "Belum ada panen tersedia.",

    // Production
    manufacturer_module: "Modul Pabrik / Produsen",
    production_rec: "Pencatatan Produksi & QC",
    source_collection: "Batch Pengumpulan Sumber",
    pick_cb: "Pilih CB...",
    input_kg: "Input Bahan Baku (kg)",
    output_units: "Output (unit / bungkus)",
    blend_notes: "Catatan Blending",
    packaging: "Kemasan",
    excise: "No. Pita Cukai (CHT)",
    quality_grade_final: "Grade Kualitas Akhir",
    ai_qc_line: "AI Quality Inspection (Proposed Integration): Grade A Super · Confidence 96.4%",
    submit_production: "Cetak QR & Commit Block (SC-003)",

    // Shipment
    distributor_module: "Modul Distributor",
    shipment_track: "Tracking Pengiriman",
    source_production: "Batch Produksi Sumber",
    pick_pb: "Pilih PB...",
    destination: "Tujuan Ritel",
    qty_units: "Jumlah Unit",
    ship_date: "Tanggal Kirim",
    eta_date: "ETA Tiba",
    temp_max: "Suhu Max (°C)",
    humidity_pct: "Kelembaban (%)",
    iot_note: "IoT Smart Lock akan aktif; sensor akan streaming ke ledger tiap 5 menit.",
    submit_shipment: "Aktifkan IoT & Buat Surat Jalan Digital",

    // Retail / sales
    retailer_module: "Modul Ritel",
    sales_qr: "Penjualan & QR Generation",
    source_shipment: "Batch Pengiriman Sumber",
    pick_sb: "Pilih SB...",
    units_received: "Unit Diterima",
    display_date: "Tanggal Dipajang",
    store_loc: "Lokasi Toko",
    submit_sales: "Finalisasi Chain & Generate QR",
    qr_auth: "QR Otentikasi Produk",
    download_qr: "Unduh QR",
    qr_hint: "QR akan otomatis dibuat setelah submit",

    // Traceability
    trace_title: "Cari & Rekonstruksi Rantai",
    trace_placeholder: "Batch ID (HB-0001 / CB-0001 / PB-0001 / SB-0001 / RB-0001) atau Product ID (PRD-XXXXXXXX)",
    search: "Cari",
    timeline_title: "Timeline Rantai Pasok",
    ledger_blocks: "Ledger Blocks",
    batch_not_found: "Batch tidak ditemukan",

    // Explorer
    explorer_title: "Blockchain Explorer",
    verify_integrity: "Verifikasi Integrity",
    integrity_valid: "✓ VALID",
    integrity_broken: "✗ RUSAK",
    integrity_not_checked: "Belum diperiksa",
    latest_blocks: "Blok Terbaru",
    chain_valid_msg: "Chain valid",
    blocks_verified: "blok terverifikasi",
    chain_broken_at: "Chain rusak pada block",
    block: "Block",
    timestamp: "Timestamp",
    prev_hash: "Previous Hash",
    curr_hash: "Current Hash",
    payload: "Payload",

    // Contracts
    contracts_title: "Smart Contracts",
    live_console: "Live Console (Auto-refresh 8s)",
    no_contract_exec: "Belum ada eksekusi smart contract.",

    // Quality
    quality_title: "IoT & AI Quality Inspection",
    proposed_integration: "PROPOSED INTEGRATION · SIMULATED SENSOR STREAM",
    temp_storage: "Suhu Storage",
    humidity: "Kelembaban",
    leaf_moisture: "Kadar Air Daun",
    normal: "✓ Normal",
    anomaly: "⚠ Anomali",
    telemetry: "Telemetri 100 Menit Terakhir",
    ai_inspection: "AI Inspection",
    classified_grade: "Grade Terklasifikasi",
    confidence: "Confidence",
    foreign_material: "Foreign Material Score",
    disease: "Disease",
    detected: "TERDETEKSI",
    not_detected: "TIDAK ADA",
    recommendation: "Rekomendasi",
    connecting_sensor: "Menghubungkan sensor IoT...",

    // Exceptions
    exceptions_title: "Exception Log",
    anomaly_detection: "Deteksi Anomali Rantai Pasok",
    resolve: "Selesaikan",
    open: "TERBUKA",
    resolved: "RESOLVED",
    resolve_action: "Tindakan penyelesaian...",
    confirm: "Konfirmasi",
    anomaly_resolved: "Anomali diselesaikan",
    no_anomaly: "Tidak ada anomali terdeteksi 🎉",
    resolve_anomaly: "Selesaikan Anomali",

    // Audit
    audit_title: "Audit Log",
    audit_sub: "Immutable Audit Trail",
    before: "Sebelum",
    after: "Sesudah",
    corrected_batch: "memperbaiki batch",
    reason_label: "Alasan",
    no_corrections: "Belum ada koreksi yang tercatat.",

    // Users
    users_title: "Manajemen Pengguna",
    admin_only: "Admin Only",
    invite_user: "Undang Pengguna",
    invite_new: "Undang Pengguna Baru",
    name: "Nama",
    initial_password: "Password Awal",
    role: "Role",
    company: "Perusahaan",
    position: "Jabatan",
    contact: "Kontak",
    create_account: "Buat Akun",
    invite_success: "Undangan terkirim & akun dibuat",
    delete_confirm: "Hapus user ini?",

    // Analytics
    analytics_title: "Analitik Rantai Pasok",
    mgmt_dashboard: "Management Dashboard",
    csv_downloaded: "CSV diunduh",
    pdf_downloaded: "PDF diunduh",
    volume_by_variety: "Volume Panen per Varietas (kg)",
    dist_by_region: "Distribusi per Wilayah",
    production_grade: "Grade Produksi",
    trend_7d: "Trend Batch 7 Hari",
    loading_analytics: "Memuat analitik...",

    // Batch detail
    back_to_trace: "← Kembali ke Traceability",
    batch_details: "Detail Batch",
    blockchain_blocks: "Blockchain Blocks",
    actor: "Aktor",
    role_field: "Role",
    loading: "Memuat...",
    required_fields: "Kolom wajib diisi",
    fill_all: "Lengkapi semua data sebelum menyimpan",
  },
  en: {
    tagline: "Blockchain Traceability",
    login_heading: "Please sign in",
    login_sub: "Use the account your admin has invited you with.",
    email: "Email",
    password: "Password",
    sign_in: "Sign in",
    verifying: "Verifying...",
    quick_fill: "Quick-fill Demo",
    public_verify: "→ Verify Product (Public)",
    live_network: "Live Network",
    validators: "3 Validators",
    welcome: "Welcome",
    dashboard_title: "Operational Dashboard",
    dashboard_sub: "Real-time overview of the tobacco supply chain — Farmer to Consumer.",
    block_height: "Block Height",
    latency: "Latency",
    validators2: "Validators",
    data_sync: "Data Sync",
    synced: "SYNCED",
    active_harvests: "Active Harvest Batches",
    collections: "Collection Batches",
    production_batches: "Production Batches",
    shipments: "Shipments",
    retail_batches: "Retail Batches",
    trace_records: "Traceability Records",
    quality_compliance: "Quality Compliance",
    open_exceptions: "Open Exceptions",
    supply_chain: "Supply Chain Visualization",
    journey: "Horizontal Batch Journey",
    search_batch: "→ Search Batch",
    verified: "✓ Verified",
    exception: "⚠ Exception",
    pending: "⚡ Pending",
    net_status: "Blockchain Network",
    healthy: "HEALTHY",
    consumer_portal: "Consumer Portal",
    logout: "Sign out",
    nav_dashboard: "Dashboard",
    nav_harvest: "Harvest Registration",
    nav_collection: "Collection",
    nav_production: "Production",
    nav_shipment: "Shipment",
    nav_sales: "Retail Sales",
    nav_trace: "Traceability",
    nav_explorer: "Blockchain Explorer",
    nav_contracts: "Smart Contracts",
    nav_quality: "IoT & Quality",
    nav_exceptions: "Exceptions",
    nav_analytics: "Analytics",
    nav_audit: "Audit Log",
    nav_users: "User Management",
    verify_heading: "Consumer Verification Portal",
    verify_sub: "Scan the QR or enter a Product ID to check authenticity of your tobacco product.",
    verify_btn: "Verify",
    authentic: "✓ AUTHENTIC PRODUCT",
    authentic_sub: "Made in Indonesia · Blockchain Verified",
    not_authentic: "✗ NOT VERIFIED",
    variety: "Variety",
    cultivation: "Cultivation Area",
    harvest_date: "Harvest Date",
    grade: "Grade",
    chain_journey: "Supply Chain Journey",
    download_cert: "Download Authenticity Certificate (PDF)",
    hero_body: "Every harvest, weighing, production, shipment, and sale is committed to the ledger as an immutable block with a SHA-256 hash.",
    map_title: "Provenance Map",
    map_from: "Origin Farm",
    map_to: "Retail Store",
    scanned_count: "Scanned",
    times: "times",
    cancel: "Cancel",
    product_not_found: "Product not found",
    camera_unavailable: "Camera unavailable",

    farmer_module: "Farmer Module",
    harvest_reg: "Tobacco Harvest Registration",
    variety_label: "Tobacco Variety",
    location_label: "Farm Location",
    gps_label: "GPS Coordinates",
    weight_kg: "Total Weight (kg)",
    plant_age: "Plant Age (days)",
    moisture_pct: "Moisture (%)",
    initial_grade: "Initial Grade",
    submit_harvest: "Publish Harvest Smart Contract (SC-001)",
    signing_block: "Signing block...",
    last_tx: "Last Transaction",
    batch_id: "Batch ID",
    block_num: "Block #",
    hash: "Hash",
    no_tx_yet: "No transactions yet. Fill in the form to record your first harvest to the ledger.",
    save_fail: "Save failed",
    saved_to_ledger: "recorded to ledger",

    collector_module: "Collector Module",
    collection_rec: "Collection Recording",
    source_harvest: "Source Harvest Batch",
    pick_hb: "Choose HB...",
    weight_received: "Weight Received (kg)",
    leaf_grade: "Leaf Grade",
    drying_method: "Drying Method",
    sort_notes: "Sorting Notes",
    submit_collection: "Sign & Forward to Manufacturer (SC-002)",
    available_harvests: "Available Harvest Batches",
    no_harvest_available: "No harvest batches available.",

    manufacturer_module: "Manufacturer Module",
    production_rec: "Production Recording & QC",
    source_collection: "Source Collection Batch",
    pick_cb: "Choose CB...",
    input_kg: "Raw Material Input (kg)",
    output_units: "Output (units / packs)",
    blend_notes: "Blending Notes",
    packaging: "Packaging",
    excise: "Excise Number (CHT)",
    quality_grade_final: "Final Quality Grade",
    ai_qc_line: "AI Quality Inspection (Proposed Integration): Grade A Super · Confidence 96.4%",
    submit_production: "Print QR & Commit Block (SC-003)",

    distributor_module: "Distributor Module",
    shipment_track: "Shipment Tracking",
    source_production: "Source Production Batch",
    pick_pb: "Choose PB...",
    destination: "Retail Destination",
    qty_units: "Quantity (units)",
    ship_date: "Ship Date",
    eta_date: "ETA",
    temp_max: "Max Temperature (°C)",
    humidity_pct: "Humidity (%)",
    iot_note: "IoT Smart Lock will engage; sensors will stream to the ledger every 5 minutes.",
    submit_shipment: "Activate IoT & Create Digital Waybill",

    retailer_module: "Retailer Module",
    sales_qr: "Sales & QR Generation",
    source_shipment: "Source Shipment Batch",
    pick_sb: "Choose SB...",
    units_received: "Units Received",
    display_date: "Display Date",
    store_loc: "Store Location",
    submit_sales: "Finalize Chain & Generate QR",
    qr_auth: "Product Authenticity QR",
    download_qr: "Download QR",
    qr_hint: "QR will be generated automatically after submit",

    trace_title: "Search & Reconstruct Chain",
    trace_placeholder: "Batch ID (HB-0001 / CB-0001 / PB-0001 / SB-0001 / RB-0001) or Product ID (PRD-XXXXXXXX)",
    search: "Search",
    timeline_title: "Supply Chain Timeline",
    ledger_blocks: "Ledger Blocks",
    batch_not_found: "Batch not found",

    explorer_title: "Blockchain Explorer",
    verify_integrity: "Verify Integrity",
    integrity_valid: "✓ VALID",
    integrity_broken: "✗ BROKEN",
    integrity_not_checked: "Not checked yet",
    latest_blocks: "Latest Blocks",
    chain_valid_msg: "Chain valid",
    blocks_verified: "blocks verified",
    chain_broken_at: "Chain broken at block",
    block: "Block",
    timestamp: "Timestamp",
    prev_hash: "Previous Hash",
    curr_hash: "Current Hash",
    payload: "Payload",

    contracts_title: "Smart Contracts",
    live_console: "Live Console (Auto-refresh 8s)",
    no_contract_exec: "No smart contract executions yet.",

    quality_title: "IoT & AI Quality Inspection",
    proposed_integration: "PROPOSED INTEGRATION · SIMULATED SENSOR STREAM",
    temp_storage: "Storage Temperature",
    humidity: "Humidity",
    leaf_moisture: "Leaf Moisture",
    normal: "✓ Normal",
    anomaly: "⚠ Anomaly",
    telemetry: "Telemetry — Last 100 Minutes",
    ai_inspection: "AI Inspection",
    classified_grade: "Classified Grade",
    confidence: "Confidence",
    foreign_material: "Foreign Material Score",
    disease: "Disease",
    detected: "DETECTED",
    not_detected: "NONE",
    recommendation: "Recommendation",
    connecting_sensor: "Connecting to IoT sensors...",

    exceptions_title: "Exception Log",
    anomaly_detection: "Supply Chain Anomaly Detection",
    resolve: "Resolve",
    open: "OPEN",
    resolved: "RESOLVED",
    resolve_action: "Resolution action...",
    confirm: "Confirm",
    anomaly_resolved: "Anomaly resolved",
    no_anomaly: "No anomalies detected 🎉",
    resolve_anomaly: "Resolve Anomaly",

    audit_title: "Audit Log",
    audit_sub: "Immutable Audit Trail",
    before: "Before",
    after: "After",
    corrected_batch: "corrected batch",
    reason_label: "Reason",
    no_corrections: "No corrections logged yet.",

    users_title: "User Management",
    admin_only: "Admin Only",
    invite_user: "Invite User",
    invite_new: "Invite New User",
    name: "Name",
    initial_password: "Initial Password",
    role: "Role",
    company: "Company",
    position: "Position",
    contact: "Contact",
    create_account: "Create Account",
    invite_success: "Invitation sent & account created",
    delete_confirm: "Delete this user?",

    analytics_title: "Supply Chain Analytics",
    mgmt_dashboard: "Management Dashboard",
    csv_downloaded: "CSV downloaded",
    pdf_downloaded: "PDF downloaded",
    volume_by_variety: "Harvest Volume by Variety (kg)",
    dist_by_region: "Distribution by Region",
    production_grade: "Production Grades",
    trend_7d: "Batch Trend — 7 Days",
    loading_analytics: "Loading analytics...",

    back_to_trace: "← Back to Traceability",
    batch_details: "Batch Details",
    blockchain_blocks: "Blockchain Blocks",
    actor: "Actor",
    role_field: "Role",
    loading: "Loading...",
    required_fields: "Required fields",
    fill_all: "Please fill in all fields before saving",
  },
};

const Ctx = createContext(null);
export const useLang = () => useContext(Ctx);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "id");
  const t = (k) => DICT[lang]?.[k] ?? DICT.id[k] ?? k;
  const toggle = () => { const next = lang === "id" ? "en" : "id"; localStorage.setItem("lang", next); setLang(next); };
  return <Ctx.Provider value={{ lang, t, toggle }}>{children}</Ctx.Provider>;
}
