import React, { createContext, useContext, useState } from "react";

const DICT = {
  id: {
    tagline: "Blockchain Traceability",
    title_hero: "Tobacco Smart Blockchain",
    subtitle_hero: "from Farm to Fork with the Authenticity",
    login_heading: "Silakan masuk",
    login_sub: "Gunakan akun yang telah diundang admin.",
    email: "Email",
    password: "Kata Sandi",
    sign_in: "Masuk",
    verifying: "Memverifikasi...",
    quick_fill: "Isi Cepat Demo",
    public_verify: "→ Verifikasi Produk (Publik)",
    live_network: "Live Network",
    validators: "3 Validators",
    welcome: "Selamat datang",
    dashboard_title: "Dasbor Operasional",
    dashboard_sub: "Ringkasan real-time rantai pasok tembakau — Petani hingga Konsumen.",
    block_height: "Block Height",
    latency: "Latency",
    validators2: "Validators",
    data_sync: "Data Sync",
    synced: "SYNCED",
    active_harvests: "Batch Panen Aktif",
    collections: "Batch Pengumpulan",
    production_batches: "Batch Produksi",
    shipments: "Pengiriman",
    retail_batches: "Ritel Terdaftar",
    trace_records: "Rekaman Traceability",
    quality_compliance: "Kepatuhan Kualitas",
    open_exceptions: "Anomali Terbuka",
    supply_chain: "Visualisasi Rantai Pasok",
    journey: "Journey Batch Horizontal",
    search_batch: "→ Cari Batch",
    stage_farmer: "Petani",
    stage_collector: "Pengepul",
    stage_manufacturer: "Pabrik",
    stage_distributor: "Distributor",
    stage_retailer: "Ritel",
    verified: "✓ Terverifikasi",
    exception: "⚠ Anomali",
    pending: "⚡ Pending",
    net_status: "Blockchain Network",
    healthy: "HEALTHY",
    consumer_portal: "Portal Konsumen",
    logout: "Keluar",
    nav_dashboard: "Dasbor",
    nav_harvest: "Registrasi Panen",
    nav_collection: "Pengumpulan",
    nav_production: "Produksi",
    nav_shipment: "Pengiriman",
    nav_sales: "Penjualan Ritel",
    nav_trace: "Traceability",
    nav_explorer: "Blockchain Explorer",
    nav_contracts: "Smart Contracts",
    nav_quality: "IoT & Kualitas",
    nav_exceptions: "Anomali",
    nav_analytics: "Analitik",
    nav_audit: "Audit Log",
    nav_users: "Manajemen User",
    verify_heading: "Portal Verifikasi Konsumen",
    verify_sub: "Scan QR atau masukkan Product ID untuk memeriksa keaslian tembakau Anda.",
    verify_btn: "Verifikasi",
    authentic: "✓ TERVERIFIKASI OTENTIK",
    authentic_sub: "Asli Indonesia · Blockchain Verified",
    not_authentic: "✗ TIDAK TERVERIFIKASI",
    variety: "Varietas",
    cultivation: "Asal Kebun",
    harvest_date: "Tanggal Panen",
    grade: "Grade",
    chain_journey: "Journey Rantai Pasok",
    download_cert: "Unduh Sertifikat Keaslian (PDF)",
    from_kebun: "Dari Kebun Temanggung",
    to_consumer: "sampai Konsumen.",
    hero_body: "Setiap panen, penimbangan, produksi, pengiriman, dan penjualan dicatat sebagai blok immutable dengan hash SHA-256 di ledger blockchain.",
  },
  en: {
    tagline: "Blockchain Traceability",
    title_hero: "Tobacco Smart Blockchain",
    subtitle_hero: "from Farm to Fork with the Authenticity",
    login_heading: "Please sign in",
    login_sub: "Use the account your admin has invited you with.",
    email: "Email",
    password: "Password",
    sign_in: "Sign in",
    verifying: "Verifying...",
    quick_fill: "Quick-fill Demo",
    public_verify: "→ Verify Product (Public)",
    live_network: "Live Network",
    validators: "3 Validators",
    welcome: "Welcome",
    dashboard_title: "Operational Dashboard",
    dashboard_sub: "Real-time overview of the tobacco supply chain — Farmer to Consumer.",
    block_height: "Block Height",
    latency: "Latency",
    validators2: "Validators",
    data_sync: "Data Sync",
    synced: "SYNCED",
    active_harvests: "Active Harvest Batches",
    collections: "Collection Batches",
    production_batches: "Production Batches",
    shipments: "Shipments",
    retail_batches: "Retail Batches",
    trace_records: "Traceability Records",
    quality_compliance: "Quality Compliance",
    open_exceptions: "Open Exceptions",
    supply_chain: "Supply Chain Visualization",
    journey: "Horizontal Batch Journey",
    search_batch: "→ Search Batch",
    stage_farmer: "Farmer",
    stage_collector: "Collector",
    stage_manufacturer: "Manufacturer",
    stage_distributor: "Distributor",
    stage_retailer: "Retailer",
    verified: "✓ Verified",
    exception: "⚠ Exception",
    pending: "⚡ Pending",
    net_status: "Blockchain Network",
    healthy: "HEALTHY",
    consumer_portal: "Consumer Portal",
    logout: "Sign out",
    nav_dashboard: "Dashboard",
    nav_harvest: "Harvest Registration",
    nav_collection: "Collection",
    nav_production: "Production",
    nav_shipment: "Shipment",
    nav_sales: "Retail Sales",
    nav_trace: "Traceability",
    nav_explorer: "Blockchain Explorer",
    nav_contracts: "Smart Contracts",
    nav_quality: "IoT & Quality",
    nav_exceptions: "Exceptions",
    nav_analytics: "Analytics",
    nav_audit: "Audit Log",
    nav_users: "User Management",
    verify_heading: "Consumer Verification Portal",
    verify_sub: "Scan the QR or enter a Product ID to check authenticity of your tobacco product.",
    verify_btn: "Verify",
    authentic: "✓ AUTHENTIC PRODUCT",
    authentic_sub: "Made in Indonesia · Blockchain Verified",
    not_authentic: "✗ NOT VERIFIED",
    variety: "Variety",
    cultivation: "Cultivation Area",
    harvest_date: "Harvest Date",
    grade: "Grade",
    chain_journey: "Supply Chain Journey",
    download_cert: "Download Authenticity Certificate (PDF)",
    from_kebun: "From Temanggung Farms",
    to_consumer: "to the Consumer.",
    hero_body: "Every harvest, weighing, production, shipment, and sale is committed to the ledger as an immutable block with a SHA-256 hash.",
  },
};

const Ctx = createContext(null);
export const useLang = () => useContext(Ctx);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "id");
  const t = (k) => DICT[lang]?.[k] ?? DICT.id[k] ?? k;
  const toggle = () => { const next = lang === "id" ? "en" : "id"; localStorage.setItem("lang", next); setLang(next); };
  return <Ctx.Provider value={{ lang, t, toggle }}>{children}</Ctx.Provider>;
}
