// Daftar Dosen Program Studi Teknologi Industri Pertanian (TIP) UNEJ + Kelompok Keilmuan
export const DOSEN_LIST = [
  { nama: "Dr. Nita Kuswardhani, S.TP., M.Eng., IPM", kk: "Manajemen Agroindustri; Supply Chain; Proses & Produksi" },
  { nama: "Prof. Dr. Ida Bagus Suryaningrat, S.TP., M.M., IPU, ASEAN Eng.", kk: "Manajemen Agroindustri; Supply Chain" },
  { nama: "Miftahul Choiron, S.TP., M.Sc., Ph.D., CIISA", kk: "Lingkungan & Energi; Proses & Produksi" },
  { nama: "Dr. Yuli Wibowo, S.TP., M.Si., IPM", kk: "Supply Chain; Manajemen Agroindustri" },
  { nama: "Dr. Bambang Herry Purnomo, S.TP., M.Si.", kk: "Supply Chain; Manajemen Agroindustri" },
  { nama: "Dr. Eka Ruriani, S.TP., M.Si.", kk: "Pangan & Produk; Proses & Produksi" },
  { nama: "Andrew Setiawan Rusdianto, S.TP., M.Si.", kk: "Proses & Produksi; Lingkungan & Energi" },
  { nama: "Winda Amilia, S.TP., M.Sc.", kk: "Supply Chain; Pangan & Produk; Manajemen Agroindustri" },
  { nama: "Bertung Suryadharma, S.ST., M.Kom.", kk: "Digital & IoT" },
  { nama: "Andi Eko Wiyono, S.TP., M.P.", kk: "Proses & Produksi; Pangan & Produk" },
  { nama: "Dr. Nidya Shara Mahardika, S.TP., M.P.", kk: "Pangan & Produk; Manajemen Agroindustri" },
  { nama: "Shinta Syafrina Endah Hapsari, S.T., M.P.", kk: "Supply Chain; Manajemen Agroindustri" },
  { nama: "Leader Firstandika, S.Si., M.T.", kk: "Proses & Produksi; Lingkungan & Energi" },
  { nama: "Lituhayu Sausan Supartiningrum Yudiansyah, S.T., M.P.", kk: "Proses & Produksi; Manajemen Agroindustri" },
  { nama: "Muhammad Arga Hita, S.T., M.Sc.", kk: "Lingkungan & Energi; Proses & Produksi" },
  { nama: "Ahib Assadam, S.TP., M.Si.", kk: "Supply Chain; Manajemen Agroindustri" },
  { nama: "Viko Nurluthfiyadi Ni'maturrakhmat, S.T., M.T.", kk: "Supply Chain; Manajemen Agroindustri" },
  { nama: "Diana Nurhayati, S.P., M.Si.", kk: "Manajemen Agroindustri" },
  { nama: "Ummu At-Ta'anny, S.T., M.P.", kk: "Supply Chain; Manajemen Agroindustri" },
  { nama: "Alif Rizki Ulil Albab, S.T., M.T.", kk: "Manajemen Agroindustri; Proses & Produksi" },
  { nama: "Suwita Tri Prihani, S.T.P., M.P.", kk: "Kewirausahaan; Manajemen Agroindustri" },
  { nama: "S. Diah Puspaningtyas, S.T., M.T.", kk: "Mutu & Keamanan Pangan; Manajemen Agroindustri" },
];
